language: julia

os:
  - linux
  - osx
  - windows
  - freebsd

julia:
  - 1.3
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email:
    recipients: abel.s.siqueira@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags
